# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - web-teknotassen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrteknotassen.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4E1435D7117D44FA8CA1763AF9783FB7 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_71D8027D65AC4C90BBC27B2AE6CE0F12 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrteknotassen.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4E1435D7117D44FA8CA1763AF9783FB7 }}/teknotassen-backend:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0AB43153C1DD4B48BADBD5427E7E8AD9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF89AB949DD440B3A79C706E6ADA795E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B8E58FE46E04513A91CFF889783002A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-teknotassen'
          slot-name: 'Production'
          images: 'acrteknotassen.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4E1435D7117D44FA8CA1763AF9783FB7 }}/teknotassen-backend:${{ github.sha }}'
          