# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - web-teknotassen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrteknotassen.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A4828F2DA4164988A843A719AE659A85 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_ADA7A961E097404EA4A9E5DF34460739 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrteknotassen.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A4828F2DA4164988A843A719AE659A85 }}/teknotassen-backend:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCB8D907233848658148E7634B26E648 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_458A3406D09D434C91C423E304CB2FCA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A56399FE480E4652A463225B5AC7AC35 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-teknotassen'
          slot-name: 'Production'
          images: 'acrteknotassen.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A4828F2DA4164988A843A719AE659A85 }}/teknotassen-backend:${{ github.sha }}'
          